version: '3.8'

services:
  backend:
    build: ./backend/flight_app
    ports:
      - "8080:8080"
    networks:
      - flight-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - flight-network

networks:
  flight-network:
    driver: bridge